# Generated by Django 2.0.9 on 2019-01-30 06:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'performance',
            },
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thevoiceapp.Performance')),
            ],
            options={
                'db_table': 'performance_score',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thevoiceapp.Team')),
            ],
            options={
                'db_table': 'team_member',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='thevoiceapp.User')),
            ],
            options={
                'db_table': 'user_admin',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='thevoiceapp.User')),
            ],
            options={
                'db_table': 'user_candidate',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='thevoiceapp.User')),
            ],
            options={
                'db_table': 'user_mentor',
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thevoiceapp.Candidate'),
        ),
        migrations.AddField(
            model_name='team',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thevoiceapp.Mentor'),
        ),
        migrations.AddField(
            model_name='performancescore',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thevoiceapp.Mentor'),
        ),
        migrations.AddField(
            model_name='performance',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thevoiceapp.Candidate'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='performancescore',
            unique_together={('performance', 'mentor')},
        ),
    ]
